import type { Invoice } from "@/modules/billing/types";

export const invoices: Invoice[] = [
  {
    id: "inv-2026-041",
    companyId: "co-nordic-ops",
    companyName: "Nordic Ops AB",
    customerId: "cust-arctic-outdoor",
    customerName: "Arctic Outdoor Co.",
    status: "draft",
    amountOre: 1850000,
    currency: "SEK",
    dueDate: "2026-04-30",
    issuedDate: "2026-04-16",
    category: "hosting",
  },
  {
    id: "inv-2026-038",
    companyId: "co-studio-fredrik",
    companyName: "Studio Fredrik",
    customerId: "cust-lagom-interior",
    customerName: "Lagom Interiör",
    status: "sent",
    amountOre: 720000,
    currency: "SEK",
    dueDate: "2026-04-24",
    issuedDate: "2026-04-10",
    category: "consulting",
  },
  {
    id: "inv-2026-031",
    companyId: "co-nordic-ops",
    companyName: "Nordic Ops AB",
    customerId: "cust-saas-atlas",
    customerName: "SaaS Atlas",
    status: "paid",
    amountOre: 340000,
    currency: "SEK",
    dueDate: "2026-04-12",
    issuedDate: "2026-03-29",
    paidDate: "2026-04-11",
    category: "subscription",
  },
];
